// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/routers": {
            "get": {
                "description": "Returns paginated list of records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "record"
                ],
                "summary": "Get records",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetRecordsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Record": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "bitNumber": {
                    "type": "string"
                },
                "block": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "fileID": {
                    "type": "integer"
                },
                "invID": {
                    "type": "string"
                },
                "invertBit": {
                    "type": "string"
                },
                "messageClass": {
                    "type": "string"
                },
                "messageID": {
                    "type": "string"
                },
                "messageLevel": {
                    "type": "string"
                },
                "messageText": {
                    "type": "string"
                },
                "messageType": {
                    "type": "string"
                },
                "mqtt": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "unitGUID": {
                    "type": "string"
                },
                "varAddress": {
                    "type": "string"
                }
            }
        },
        "handlers.GetRecordsResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Record"
                    }
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Records Service API",
	Description:      "API for viewing TSV files",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
